### PR TITLE
[Experiment] Listen for position updates from the main process

### PR DESCRIPTION
**Pull request by bernd**
**EXPERIMENT - DO NOT MERGE!**

This exposes the electron IPC mechanism to angular via the ElectronIpcService.

Might be used as an example to get position updates from the main process into the angular application to be able to use nodejs APIs like child processes.

### CODE REVIEW

**Comment by niczem** [comment]
@cyroxx

**Comment by bernd** [comment]
@niczem @JoshuaKrueger why has this been merged?

**Comment by niczem** [comment]
This happened by accident because the branch in this pull request was based on this branch for some reason:
https://github.com/sea-watch/SAR-Client/pull/151

I deleted the ipc parts from the branch again. Sorry about that!
Is there an easy way to recreate your pull request?

**Comment by bernd** [comment]
Okay, next time please just use `git revert` on the commit that got merged accidentally. This ensures that all changes from that commit will be removed.

I did that in 31d6cd8 to remove some leftover things in `src/index.html` and `src/index.js`.

**Comment by bernd** [comment]
We can just leave this PR closed, we can always look at this PR if we want to look at the changes later. :smiley:

**Comment by niczem** [comment]
Ok:) Sorry about that!

We probably need this pr when we are closer with the gps dongle. 

I added a first ipc service in this pr:
https://github.com/sea-watch/SAR-Client/pull/146/files

**Pull request merged**
