### PR TITLE
[WIP] Switch vehicle locations storage to a different DB engine

### PR DESCRIPTION
**Pull request by bernd**
**This is WIP, do not merge yet**

This PR switches the locations storage from PouchDB to [Dexie.js](http://dexie.org/). Unfortunately, PouchDB query performance becomes pretty bad with lots of database entries. Also, replicating all locations to all clients is not really needed and consumes lots of bandwith.

Dexie.js also uses IndexedDB under the hood but has way better query performance. (1200 ms vs. 3 ms for the same data set) The idea is the following:

1. We store the vehicle locations with Dexie.js instead of PouchDB
1. On app startup, we request the latest location for every vehicle (by using PouchDB as CouchDB client) and store them via Dexie.js
1. We subscribe to the changes feed of the remote CouchDB and store updated vehicle locations in the local storage with Dexie.js

#### Open Tasks

- [ ] Switch case locations to a different database and migrate all existing case locations
- [x] Fix packaging issue with Dexie.js

### CODE REVIEW

**Comment by niczem** [comment]
Thanks, awesome!
Do you mind if I merge this request, and create an issue for "Switch case locations to a different database and migrate all existing case locations"?

**Comment by bernd** [comment]
@niczem If everything else works, go ahead!

**Comment by niczem** [comment]
Just checked it, looks good! :)

**Comment by niczem** [comment]
#215 added

**Pull request merged**
