### PR TITLE
maptiles added

### PR DESCRIPTION
**Pull request by niczem**

### CODE REVIEW

**Comment by bernd** [comment]
@niczem Why are we adding a zip file instead of extracting the files? Or does the app do that automatically?

**Comment by niczem** [comment]
because there are quite a lot files inside the maptiles folder:

```
$ find MapQuest/ -print | wc -l 
   11249
```

I added a postinstallation script to the package.json:

`
    "postinstall": "unzip ./src/unzip_me.zip && rm -rf ./src/unzip.me"
`

**Comment by bernd** [comment]
>I added a postinstallation script to the package.json:
>
> "postinstall": "unzip ./src/unzip_me.zip && rm -rf ./src/unzip.me"

Fair enough. I would suggest renaming the `unzip_me.zip` to something like `map-tiles.zip` so it's clear what's inside. And maybe move it into the `data/` folder as well. 

The command extracts the `MapQuest` folder inside the root folder instead of inside the `src/` folder. I guess we should also add the extracted `MapQuest` folder and the `__MACOSX` folder to `.gitignore`.

**Comment by bernd** [comment]
@niczem I added a commit to adjust the PR according to my comments.

**Pull request merged**
